lane :test_list do
  list username:"prasopes.kurmiptak@gmail.com"
end

lane :test_add_client do
  add_client username:"prasopes.kurmiptak@gmail.com"
end

lane :test_delete_client do
  delete_client username:"prasopes.kurmiptak@gmail.com"
end

lane :test_upload_certificate do
  upload_certificate username:"prasopes.kurmiptak@gmail.com", p12_path:"testfiles/production_cz.ackee.enterprise.a4e.majales.beta.p12"
end

lane :test_download_config do
  download_config username:"prasopes.kurmiptak@gmail.com"
end

# lane :test_list do
#   firebase
# end