lane :test_list do
  firebase_list
end

lane :test_add_client do
  firebase_add_client
end

lane :test_delete_client do
  firebase_delete_client
end

lane :test_upload_certificate do
  firebase_upload_certificate
end

lane :test_download_config do
  firebase_download_config
end
